// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEIuAxel0tX7nEVdpJG1P9SP8GK05N7uM',
    appId: '1:400342809067:web:4b502d0c7c15c98b7a81ae',
    messagingSenderId: '400342809067',
    projectId: 'cmsc23-bmdamian',
    authDomain: 'cmsc23-bmdamian.firebaseapp.com',
    storageBucket: 'cmsc23-bmdamian.appspot.com',
    measurementId: 'G-DYBP1WCP0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5MKmLmPg8tsAZwrHD9ihyeTTRiO0jeEw',
    appId: '1:400342809067:android:6ba33110492329e97a81ae',
    messagingSenderId: '400342809067',
    projectId: 'cmsc23-bmdamian',
    storageBucket: 'cmsc23-bmdamian.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUzYHsY9MtpJfx_JNJegiCjDsFfZD0uFQ',
    appId: '1:400342809067:ios:8ffe41bbc0070bdb7a81ae',
    messagingSenderId: '400342809067',
    projectId: 'cmsc23-bmdamian',
    storageBucket: 'cmsc23-bmdamian.appspot.com',
    iosClientId:
        '400342809067-a343j5lofdr2em9f5544bps3n2pjq8d6.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUzYHsY9MtpJfx_JNJegiCjDsFfZD0uFQ',
    appId: '1:400342809067:ios:8ffe41bbc0070bdb7a81ae',
    messagingSenderId: '400342809067',
    projectId: 'cmsc23-bmdamian',
    storageBucket: 'cmsc23-bmdamian.appspot.com',
    iosClientId:
        '400342809067-a343j5lofdr2em9f5544bps3n2pjq8d6.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
